name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        {
          dir:
            [
              "./command/HomeAutomationInc",
              "./state/MightyGumball",
              "./proxy/MightyGumball",
              "./proxy/ExpensiveMath",
              "./proxy/ObjectvilleMatchmaking",
              "./bridge/UniversalRemoteControl",
              "./chain-of-responsibility/MightyGumballMailing",
              "./flyweight/LandscapeDesign",
              "./interpreter/BoolExParser",
              "./mediator/HouseOfTheFuture",
              "./memento/TicTacToe",
              "./composite/ObjectvilleFood",
              "./abstract-factory/MazeGame",
              "./abstract-factory/PizzaStore",
              "./singleton/ChocOHolic",
              "./template-method/StarbuzzCoffee",
              "./iterator/ObjectvilleFood",
              "./adapter/DuckAdapter",
              "./facade/HomeTheater",
              "./builder/Patternsland",
              "./factory-method/PizzaStore",
              "./observer/WeatherStation",
              "./prototype",
              "./strategy",
              "./decorator",
            ],
        }
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
